version: '2'
services:
    daspanel-mariadb:
        image: daspanel/mariadb
        volumes:
            - ./data:/opt/daspanel/data
        networks:
            - backend
        ports:
            - "3306:3306"
        env_file:
            - daspanel.env
networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


