
version: '2'
services:
    daspanel-mariadb:
        build:
            context: .
            dockerfile: Dockerfile
        image: daspanel/mariadb
        volumes:
            - daspanel-data:/opt/daspanel/data
        networks:
            - backend
        env_file:
            - daspanel.env
        ports:
            - "3306:3306"

volumes:
    daspanel-data:
        external:
            name: daspanel-data

networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


