#!/usr/bin/with-contenv sh

# Installation UUID must be informed
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    exit 1
fi

case "$DASPANEL_WAIT_FOR_API" in
    YES|yes|Yes)
        echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Waiting 60 seconds for API: $0" >&2
        /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
        result=$?
        if [ ! $result -eq 0 ] ; then
            echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
            exit 1
        fi
        ;;
    *) 
        echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Container not need to wait API become online: $0" >&2
        exit 1
        ;;
esac

# Get system configs from API server and set env variables
SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
result=$?
if [ ! $result -eq 0 ] ; then
    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Unable to get tenant configuration from API server: $0" >&2
    exit 1
fi

exec /usr/bin/mysqld_safe --user=daspanel --console --port=3306


